spring.application.name=lv3-final-mission

spring.datasource.url=jdbc:mysql://10.0.100.44:3306/lv3?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true

security.jwt.token.secret-key=aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggg
security.jwt.token.expire-length=3600000

spring.sendgrid.api=https://api.sendgrid.com/v3/mail/send
spring.sendgrid.from=dydktest1@gmail.com
spring.sendgrid.api-key=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
